name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VITE_BESTBUY_API_URL: ${{ vars.VITE_BESTBUY_API_URL }}
  VITE_BESTBUY_API_KEY: ${{ vars.VITE_BESTBUY_API_KEY }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run preview
